user_name: jialun
home_path_local: "{{ lookup('env', 'HOME') }}"
ssh_key_local: "{{ home_path_local }}/.ssh/id_rsa"
ssh_key_public_local: "{{ home_path_local }}/.ssh/id_rsa.pub"

gcp_project: bosch-150126
gcp_zone: europe-west1-b
service_account_file: "{{ home_path_local }}/secret/bosch-150126-1836c1259684.json"

node_count: 3
master_count: 1

app_namespace: default
app_replica_count: 2
app_name: getting-started
