- name: Deploy MySQL using Helm
  kubernetes.core.helm:
    name: mysql
    chart_ref: bitnami/mysql
    release_namespace: "{{ app_namespace }}"
    create_namespace: true
    values:
      global:
        storageClass: "{{ db_storage_class_name }}"

- name: Wait for MySQL to become available
  ansible.builtin.pause:
    seconds: 30
