- name: Add the Bitnami Helm repository
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: https://charts.bitnami.com/bitnami

- name: Update Helm repositories
  command: helm repo update

- name: Deploy MySQL using Helm
  kubernetes.core.helm:
    name: mysql
    chart_ref: bitnami/mysql
    release_namespace: "{{ mysql_namespace }}"
    create_namespace: yes
    values:
      global:
        storageClass: "{{ storage_class_name }}"
      primary:
        service:
          type: ClusterIP
          clusterIP: "{{ mysql_host }}"

