- name: Clone the repository
  ansible.builtin.git:
    repo: "{{ app_repository_url }}"
    dest: "{{ app_repository_dest }}"
    version: "master"

- name: Copy Dockerfile to the project directory
  ansible.builtin.copy:
    src: Dockerfile
    dest: "{{ app_repository_dest }}/Dockerfile"
    mode: "644"

- name: Build the Docker image
  community.docker.docker_image:
    build:
      path: "{{ app_repository_dest }}"
    name: "{{ app_docker_image_name }}"
    tag: "{{ app_docker_image_tag }}"
    source: build

- name: Push Docker image to Docker Hub
  community.docker.docker_image:
    name: "{{ app_docker_image_name }}"
    tag: "{{ app_docker_image_tag }}"
    push: true
    repository: "{{ app_docker_image_name }}"
    source: local
