- name: Copy Helm Chart to Remote Host
  ansible.builtin.copy:
    src: ../helm-chart
    dest: "{{ ansible_env.HOME }}"
    mode: '755'

- name: Deploy App
  kubernetes.core.helm:
    name: "{{ app_name }}"
    chart_ref: "{{ ansible_env.HOME }}/helm-chart"
    release_namespace: "{{ app_namespace }}"
    create_namespace: true
    values:
      replicaCount: "{{ app_replica_count }}"
      mysql:
        host: "mysql.{{ app_namespace }}.svc.cluster.local"
