- name: Create APP deployment
  kubernetes.core.k8s:
    state: present
    namespace: "{{ app_namespace }}"
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "{{ app_name }}"
        labels: "{{ app_labels }}"
      spec:
        replicas: "{{ replica_count }}"
        selector:
          matchLabels: "{{ app_labels }}"
        template:
          metadata:
            labels: "{{ app_labels }}"
          spec:
            containers:
            - name: "{{ app_name }}"
              image: "{{ docker_image_name }}:{{ docker_image_tag }}"
              ports:
              - containerPort: 3000
              env:
              - name: MYSQL_HOST
                value: "{{ mysql_host }}"
              - name: MYSQL_USER
                value: "{{ mysql_user }}"
              - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: mysql
                    key: mysql-root-password
              - name: MYSQL_DB
                value: "{{ mysql_db }}"

- name: Create APP service
  kubernetes.core.k8s:
    state: present
    namespace: "{{ app_namespace }}"
    definition:
      kind: Service
      apiVersion: v1
      metadata:
        name: "{{ app_name }}-service"
      spec:
        selector: "{{ app_labels }}"
        type: ClusterIP
        ports:
        - port: 3000
          targetPort: 3000
