- name: Deploy NGINX Ingress Controller
  kubernetes.core.helm:
    name: ingress-nginx
    chart_ref: bitnami/nginx-ingress-controller
    release_namespace: ingress-nginx
    create_namespace: true
    values:
      service:
        type: NodePort
        nodePorts:
          http: 32080
          https: 32443

- name: Wait for NGINX Ingress Controller to become available
  ansible.builtin.pause:
    seconds: 30
