# - name: Build Docker image for APP
#   import_tasks: build_app.yml
#   become: false
#   delegate_to: localhost

- name: Create ingress
  ansible.builtin.import_tasks: create_ingress.yml
  when: inventory_hostname in groups['kube-master']
  run_once: true

- name: Create APP
  ansible.builtin.import_tasks: create_app.yml
  when: inventory_hostname in groups['kube-master']
  run_once: true
