- name: Initialize the Kubernetes cluster
  shell: kubeadm init --pod-network-cidr={{ pod_network_cidr }}

- name: Create .kube directory
  file:
    path: "~/.kube"
    state: directory
    mode: '600'

- name: Copy admin.conf to user's kube config
  copy:
    src: "/etc/kubernetes/admin.conf"
    dest: "~/.kube/config"
    remote_src: yes
    mode: '600'
