- name: Download Helm install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '700'

- name: Execute Helm install script
  ansible.builtin.shell:
    cmd: /tmp/get_helm.sh
    creates: /usr/local/bin/helm
