- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker repository
  apt_repository:
    repo: "deb https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Docker
  apt:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Start Docker service, if not
  service:
    name: docker
    state: started

- name: Ensure /etc/containerd directory exists
  file:
    path: /etc/containerd
    state: directory

- name: Generate default containerd configuration
  shell: containerd config default
  register: containerd_config

- name: Write the containerd config to file
  copy:
    dest: /etc/containerd/config.toml
    content: "{{ containerd_config.stdout }}"

- name: Configure Cgroup
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^(\s*)SystemdCgroup\s*=\s*false'
    line: '\1SystemdCgroup = true'
    backrefs: yes

- name: Restart containerd
  systemd:
    name: containerd
    state: restarted
