- name: Add Kubernetes GPG key
  apt_key:
    url: "https://pkgs.k8s.io/core:/stable:/v{{ k8s_version_number }}/deb/Release.key"

- name: Add Kubernetes repository
  apt_repository:
    repo: "deb https://pkgs.k8s.io/core:/stable:/v{{ k8s_version_number }}/deb/ /"

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Kubernetes packages
  apt:
    name:
    - kubelet
    - kubeadm
    - kubectl

- name: Hold Kubernetes packages
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
  - kubelet
  - kubeadm
  - kubectl
