- name: Deploy Tigera operator
  kubernetes.core.k8s:
    src: "https://raw.githubusercontent.com/projectcalico/calico/v3.27.2/manifests/tigera-operator.yaml"

- name: Deploy Calico custom resources
  kubernetes.core.k8s:
    src: "https://raw.githubusercontent.com/projectcalico/calico/v3.27.2/manifests/custom-resources.yaml"

- name: Remove control-plane taint from all nodes
  command: "kubectl taint nodes --all node-role.kubernetes.io/control-plane-"
