- name: Disable Swap
  ansible.builtin.command: swapoff -a
  changed_when: false

- name: Install required packages
  ansible.builtin.apt:
    name:
      - python3-kubernetes
      - git
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg

- name: Ensure /etc/apt/keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "755"
