- name: Disable Swap
  ansible.builtin.command: swapoff -a
  changed_when: false

- name: Enable IP forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: 1
    reload: true
    sysctl_set: true

- name: Load br_netfilter module
  community.general.modprobe:
    name: br_netfilter

- name: Ensure bridged network traffic is passed to iptables
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    reload: true
    sysctl_set: true
  loop:
    - { name: net.bridge.bridge-nf-call-iptables, value: 1 }
    - { name: net.bridge.bridge-nf-call-ip6tables, value: 1 }

- name: Install required packages
  ansible.builtin.apt:
    name:
      - python3-kubernetes
      - git
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
    autoremove: true
    autoclean: true

- name: Ensure /etc/apt/keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "755"
