- name: Disable Swap
  ansible.builtin.command: swapoff -a
  changed_when: false

- name: Enable IP forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: 1
    reload: true
    sysctl_set: true

- name: Load br_netfilter module
  community.general.modprobe:
    name: br_netfilter

- name: Ensure bridged network traffic is passed to iptables
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    reload: true
    sysctl_set: true
  loop:
    - { name: net.bridge.bridge-nf-call-iptables, value: 1 }
    - { name: net.bridge.bridge-nf-call-ip6tables, value: 1 }

- name: Install required packages for all nodes
  ansible.builtin.apt:
    name:
      - git
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
      - make
      - python3-pip
    autoremove: true
    autoclean: true

- name: Install required packages for master node
  ansible.builtin.pip:
    name:
      - kubernetes
      - pexpect
      - ansible
      - ansible-runner
      - ansible-runner-http
      - openshift
  when: inventory_hostname in groups["kube_master"]

- name: Remove the existing Go directory
  ansible.builtin.file:
    path: /usr/local/go
    state: absent
  when: inventory_hostname in groups["kube_master"]

- name: Download Go tarball
  ansible.builtin.get_url:
    url: https://go.dev/dl/go1.21.9.linux-amd64.tar.gz
    dest: /tmp/go1.21.9.linux-amd64.tar.gz
    mode: "644"
  when: inventory_hostname in groups["kube_master"]

- name: Extract Go tarball
  ansible.builtin.unarchive:
    src: /tmp/go1.21.9.linux-amd64.tar.gz
    dest: /usr/local
    remote_src: true
    extra_opts:
      - --strip-components=1
  when: inventory_hostname in groups["kube_master"]

- name: Add Go to PATH
  ansible.builtin.lineinfile:
    path: /etc/profile
    line: "export PATH=$PATH:/usr/local/go/bin"
    create: true
    state: present
    mode: "644"
  when: inventory_hostname in groups["kube_master"]

- name: Ensure /etc/apt/keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "755"
